language: python

python:
  - "3.5"
  - "3.6"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

before_script:
  - psql -c "create user ormdbuser with password 'ormDbPass';" -U postgres
  - psql -c "create database asyncorm;" -U postgres
  - psql -c "grant all privileges on database asyncorm to ormdbuser;" -U postgres
  - psql -c "alter user ormdbuser with superuser;" -U postgres

services:
  - postgresql

# command to install dependencies
install: make setup

activate: pipenv shell -c

# command to run tests
script:
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff . ; fi
